# frozen_string_literal: true

source 'https://rubygems.org'

ruby file: '.ruby-version'

gem 'activerecord'
gem 'asciidoctor'
gem 'asciidoctor-pdf'
gem 'awesome_print'
gem 'bcrypt'
gem 'coderay'
gem 'csv'
gem 'json'
gem 'pygments.rb'
gem 'rake'
gem 'rouge'
gem 'rubocop'
gem 'rubyzip'
gem 'sqlite3'
gem 'thor'
gem 'thread_safe'
gem 'unicode'
gem 'unicode-display_width'
gem 'webrick'
