
[glossary]
[[_glossary]]
== 用語集

変換ルール:: 前工程のモデルから後工程モデル、設計のモデルからコードなど、異なる工程の間には、表記や意味に違いが生じる。このとき、それぞれの工程の成果物の要素（モデルの要素）同士を対応づけると、成果物のつながりが確保できる。そのような対応づけを「変換ルール」と呼ぶ。

マジックナンバー（magic number）:: 直接数値のまま使っていて、値の意味がわからない識別子番号や数値定数のこと。 `const` 修飾子やマクロ定義を使って名前をつけることで、わかりやすくする対処方法がよく用いられる。

ドメイン（domain, 問題領域）:: あるシステムにおいて取り扱う必要があることがらが複数の領域に渡る場合、領域ごとに使われることばや隣接する領域によってそのシステムを区分けしたほうがよい。その分けた領域のことを「ドメイン（問題領域）と呼ぶ。領域に分けることを「ドメイン分割（domain separation）」と呼ぶ。一般に、システムやサブシステムは複数のドメインによって構成される。
たとえば、自動搬送ロボットを使った運搬システムの場合、運搬業務としては荷物を運ぶ手順、自動搬送ロボットには運搬に使う装置としての走行動作や外部との操作や通信、自動搬送ロボットを構成するデバイスではモーターを動かすというように、それぞれが使うことばが異なっており、これらは異なるドメインとみなせる。

ドメイン分割（domain separation）:: 「ドメイン」を参照。

サブシステム（subsystem）:: あるシステムにおいて、開発単位が異なる（別のプログラムに分かれる、別途開発のライブラリなど）や、操作者や通信が介在することで動作が区切られるような場合、分けたそれぞれをそのシステムの「サブシステム」と呼ぶ。サブシステムに分けることを「サブシステム分割（subsystem separation）」と呼ぶ。一般に、サブシステムは復数のドメインによって構成される。
たとえば、PCによる管制局と自動搬送ロボットで構成される自動搬送システムを考えると、管制局、自動搬送ロボットともに運搬業務のことばを扱う運搬業務のドメインを持つが、開発単位が異なり通信も介在するのでそれぞれサブシステムとみなせる。

サブシステム分割（subsystem separation）:: 「サブシステム」を参照。

ロバストネス図（robustness diagram）:: ロバストネス分析に用いる記法。クラスについて「バウンダリ」「エンティティ」「コントロール」の3種類のステレオタイプと専用のアイコンを与え、ここにアクターを加えたクラス図を描くことで構成要素を探しやすくする。

ロバストネス分析（robustness analisys）:: システムの構成要素は「バウンダリ」「エンティティ」「コントロール」の3種類に大別できると考え、これらを探すことでシステムの構成要素を抽出しようとする分析方法。記法として「ロバストネス図」を用いる。図の要素の接続関係には、アクターはバウンダリとしか接続が持てない、エンティティはコントロールを介してしか他とつながることができないなどの制約があり、この制約によって構成要素を探しやすくなっている。

オブジェクト図（object diagram）:: システムの構成要素を、実際に登場する具体的な要素（オブジェクト）を使って表した図。インスタンス図とも呼ばれる。


インスタンス図（instance diagram）:: 「オブジェクト図」を参照。
